### ISSUE TITLE
"bind" attribute does not validate, replace with "data-bind"

### ISSUE THREAD

**Issue by troygoode** [weepy/o_O#15]
http://validator.w3.org/check?uri=http%3A%2F%2Fpastehtml.com%2Fview%2Fbsono2o4e.html&charset=%28detect+automatically%29&doctype=Inline&group=0

Invalid HTML:
http://pastehtml.com/view/bsono2o4e.html

**Comment by troygoode** [comment]
Here is an example of the above document passing validating by changing to data-bind (though it breaks o_O currently):

http://validator.w3.org/check?uri=http%3A%2F%2Fpastehtml.com%2Fview%2Fbspnasvaz.html&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3

Valid HTML:
http://pastehtml.com/view/bspnasvaz.html

**Comment by weepy** [comment]
hmmm - personally i'm w/e about validating. we could add something to allow a user to change the binding attribute name

**Comment by troygoode** [comment]
I'm generally w/e about my apps validating, but I don't think a library/framework should be. We should do the right thing by default ("data-bind") and potentially let people set an option to switch to an invalid attribute if they'd prefer it ("bind"). Maybe:

``` javascript
o_O.bindingAttribute = 'bind';
```

?

**Comment by weepy** [comment]
+1

**Comment by weepy** [comment]
done
