### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by weepy** [weepy/o_O#19]
badly needs some docs

what's the best format and style ?

**Comment by troygoode** [comment]
got a good start in pull request #24

**Comment by weepy** [comment]
maybe some nice HTML to `borrow` : http://visionmedia.github.com/jog/

**Comment by troygoode** [comment]
that HTML is generated via github's new gh-pages generator (which supports templates, including that one). so totally borrowable

**Comment by troygoode** [comment]
https://github.com/blog/1081-instantly-beautiful-project-pages

**Comment by weepy** [comment]
sweet http://weepy.github.com/o_O/

On Mon, Apr 2, 2012 at 10:10 PM, Troy Goode
reply@reply.github.com
wrote:

**Comment by troygoode** [comment]
very nice!
