### ISSUE TITLE
List browser compatability

### ISSUE THREAD

**Issue by dhm116** [weepy/o_O#2]
It would be nice if you could test and list browser compatibility somewhere. For example, this works in Chrome 16.x but not IE7.

**Comment by weepy** [comment]
Unfort I don't have access to windows . Do you know the error that occurs in IE7 ?

**Comment by weepy** [comment]
There's also a test HTML that might be worth running : test/mocha.html

**Comment by dhm116** [comment]
If I load the _random.html example, I get these errors:

``` html
SCRIPT438: Object doesn't support property or method 'forEach' 
o_O.js, line 210 character 5
```

``` html
SCRIPT5007: Unable to get value of the property '_id': object is null or undefined 
o_O.js, line 323 character 3
```

The todos sample produced:

``` html
SCRIPT438: Object doesn't support property or method 'indexOf' 
o_O.js, line 135 character 5
```

I encountered similar errors when I attempted to integrate o_O in to my existing app and view on IE7.

It appears as though IE7/IE8 have issues, however IE9 seems to work sometimes and not others.

**Comment by weepy** [comment]
k - I just pushed a fix for forEach and indexOf

**Comment by dhm116** [comment]
I ran the mocha tests in IE7 (after downloading and modifying remote file references) and everything appears to have passed.

When I run either _random or the todos example, the error is now:

``` html
SCRIPT438: Object doesn't support property or method 'map' 
o_O.js, line 231 character 7
```

The _random.html sample still complains about:

``` html
SCRIPT5007: Unable to get value of the property '_id': object is null or undefined 
o_O.js, line 441 character 3
```

**Comment by weepy** [comment]
ok - pushed a fix

On Fri, Feb 10, 2012 at 3:08 PM, dhm116
reply@reply.github.com
wrote:

**Comment by dhm116** [comment]
Perhaps using something like what is suggested [here](http://stackoverflow.com/questions/2790001/fixing-javascript-array-functions-in-internet-explorer-indexof-foreach-etc) - may be a cleaner solution than your latest commit, which is explicitly overriding the functions even if they are built in.

I've also put the suggested solution in a gist [here](https://gist.github.com/1790197) (would LOVE to know how to embed gists in comments)

**Comment by weepy** [comment]
Actually it's not overwriting them it's wrapping them:

"function indexOf(array, obj, start) {"

On Fri, Feb 10, 2012 at 3:27 PM, dhm116
reply@reply.github.com
wrote:

**Comment by weepy** [comment]
did that fix work ?

**Comment by dhm116** [comment]
Looking much better!

I don't think the issue with '_id' or 'id' is related to the naming of the property. I still get the same error, which means that, for some reason, the object instance is null.

``` html

SCRIPT5007: Unable to get value of the property 'id': object is null or undefined 
o_O.js, line 444 character 3
```

This happens even on IE9, so something else is going on here...

**Comment by weepy** [comment]
odd - I'll need to debug it properly.

On Fri, Feb 10, 2012 at 4:01 PM, dhm116
reply@reply.github.com
wrote:

**Comment by dhm116** [comment]
OK, turns out that 'object is null or undefined' issue was the result of a trailing comma:

``` javascript

var company = {
  people: o_O.collection([
    new Person('Bobby', 'Reado', 30 ),
    new Person('Bobby2', 'Readoo', 301, "green"),
  ])
}
```

as opposed to:

``` javascript

var company = {
  people: o_O.collection([
    new Person('Bobby', 'Reado', 30 ),
    new Person('Bobby2', 'Readoo', 301, "green")
  ])
}
```

Thanks for addressing the other errors! I think that probably closes this issue unless anybody else has found anything.

**Comment by weepy** [comment]
cool - added a section in Readme
