### ISSUE TITLE
consider supporting .push as a synonym for .add on o_O.Collection 

### ISSUE THREAD

**Issue by troygoode** [weepy/o_O#21]
While they aren't quite the same as an array, it would be nice if most of your code could work with a Collection without having to be aware of the differences (same reasoning as to why you allow .forEach in addition to .add as well, I assume).

**Comment by weepy** [comment]
forEach is so that foreach works on Array and a Collection

not sure it's sensible to have synonyms at this stage - one or the other is better.

**Comment by troygoode** [comment]
my vote would be to drop .add and .each in favor of .push and .forEach. it makes the library more intuitive, since you don't have to learn a new API for collections

**Comment by troygoode** [comment]
resolved by a commit in Pull Request #24

**Comment by weepy** [comment]
good stuff - I think we just need to figure out what a collection really is. Is it an array or a set ? Perhaps an array is more useful. So what should happen with .find(id) ? 
Should it be renamed to o_O.array ? or o_O.list ?

**Comment by weepy** [comment]
great stuff
