### ISSUE TITLE
fix Examples/Guides/Select

### ISSUE THREAD

**Issue by troygoode** [weepy/o_O#25]
[http://weepy.github.com/o_O/examples/guide/index.html](http://weepy.github.com/o_O/examples/guide/index.html)

**Bug:** The dropdowns are defaulting to "pig" and "Ten" (the first values in each option list rather than the value specified by the `farm` object.

``` javascript
var farm = { 
  animal: o_O('cow'), 
  number: o_O(20) 
}
```

**Comment by weepy** [comment]
this is fixed. problem was because value was being set before the options were being set. I've reversed the order in the HTML. I don't know if we'd want to fix this, but one way would be to process the .change in the next event loop.

**Comment by weepy** [comment]
merged
