### ISSUE TITLE
submit Todos example to TodoMVC

### ISSUE THREAD

**Issue by troygoode** [weepy/o_O#26]
[http://addyosmani.github.com/todomvc/](http://addyosmani.github.com/todomvc/)

**Comment by weepy** [comment]
great idea... just a lil more polish

**Comment by weepy** [comment]
might be good to rewrite it - could be alot simpler i think

**Comment by weepy** [comment]
@weepy Sure, send us a pull request and we'll consider it for inclusion :)

But before you do, it would be great if you could do the following:
- Use the latest template.
- Make sure you follow the newly released [App Specification](https://github.com/addyosmani/todomvc/wiki/App-Specification).
  Please let me know if anything is unclear or could be improved. It's not field tested yet. The [spine.js example](https://github.com/addyosmani/todomvc/pull/127), not yet landed, can be used as a reference.
- This project uses tab indention and follows the [Idiomatic guide](https://github.com/rwldrn/idiomatic.js) to writing JavaScript. Please ensure your code follows this closely. If something is unclear, follow the existing style. Use double-quotes in HTML and single-quotes in JS and CSS.

I'll review it more thoroughly when the above changes are implemented :D

**Comment by weepy** [comment]
done
