### ISSUE TITLE
oO

### ISSUE THREAD

**Issue by weepy** [weepy/o_O#27]
is oO any easier to type or look at ?

**Comment by weepy** [comment]
candidates 
- oo
- o_O
- o0
- oO

first is easiest to type. second is the most iconic

**Comment by troygoode** [comment]
I really like `o_O` as it is, but people always ask me how to pronounce it...

**Comment by weepy** [comment]
I call it funnyface. Maybe we should make that it's name

**Comment by weepy** [comment]
added to README

**Comment by RihanArfan** [comment]
o_O
