### ISSUE TITLE
Redis style collections

### ISSUE THREAD

**Issue by weepy** [weepy/o_O#28]
Instead of making a one size fits all collection, we could go down the route of having more simpler collection models. E.g.

```
o_O.array( ... )   // array with pop/push etc
o_O.list( ... )       // i.e. list (set)  with add, remove
o_O.zlist( ... )     // i.e. sorted list (set) with add, remove
```

**Comment by troygoode** [comment]
+1

**Comment by weepy** [comment]
moved list to a seperate file. should probably be a different name 

o_O.set ?
