### ISSUE TITLE
inserting bound array correctly

### ISSUE THREAD

**Issue by weepy** [weepy/o_O#31]
current implementation rerenders the whole list upon each write regardless ?? :

```
proto.renderOne = function(item, $el) {
  $(getTemplate($el)).each(function(i, elem) {
    var $$ = $(elem)
    $$.appendTo($el)
    o_O.bind(item, $$)
  })
}
```

Ideally we'd like to insert after the previous element

**Comment by weepy** [comment]
I've started by changing the renderOne function sig : <code>proto.renderOne = function(item, $el, index) </code>

But I think that we also need to change the <code>add</code> function sig to use something like 

```
var add = function(col, o, index) { 
  ... 
  o.emit('add', o, col, index)
}
```

and renderOne to be something like :

```
proto.renderOne = function(item, $el, index) {
  var $$ = $(elem)
  var prev = this.at(index-1)

  prev 
    ? $$.insertAfter($(prev.el))
    : $$.prependTo($el)

   o_O.bind(item, $$)
}
```

**Comment by troygoode** [comment]
should be able to close this now

**Comment by weepy** [comment]
yep.
