### ISSUE TITLE
API to get the element bound to a model property.

### ISSUE THREAD

**Issue by nevf** [weepy/o_O#55]
Given:

```
person = {
  firstName: o_O('Michael'),
  surName: o_O('Jackson'),
}
o_O.bind(person, '#person');

<div id="#person">
  <div data-bind="text: fullName()"></div>
  <div data-bind="text: age()"></div>
</div>
```

is there a way I can get the dom element bound to person.firstname?

Thanks,
Neville

**Comment by weepy** [comment]
Does this work ? 

<div data-bind="text: firstName"></div>

**Comment by nevf** [comment]
@weepy I assume something went astray with your reply as I can't see any code etc.

**Comment by weepy** [comment]
```
person = {
  firstName: o_O('Michael'),
  surName: o_O('Jackson'),
}
o_O.bind(person, '#person');

<div id="#person">
  <div data-bind="text: firstName"></div>
</div>
```

**Comment by nevf** [comment]
How is this enabling me to get the `<div data-bind="text: firstName"></div>` element?

**Comment by weepy** [comment]
I'm sorry - I don't think I understand the question. Can you restate ?

**Comment by nevf** [comment]
I thought there may have been a misunderstanding. Given your example or mine what I want to do is:
`var $firstname = o_O.element( person.firstname )` which would return the `<div data-bind="text: firstName"></div>` element.

So once I've created the model I don't need to know the explicit dom elements any more, instead I can retrieve same using the model properties.  

Hope that's clearer.

**Comment by weepy** [comment]
there's not an explicit way to do that. You have access to this.el which is the original bound element. So you could do $(this.el).find('div) for example.

**Comment by nevf** [comment]
Ok, could I please put in a feature request to implement this? 

What I'm trying to achieve is to reduce the knowledge of the markup to a minimum. I figured o_O's model has worked out the dom element associated with each model property, so let it give this back to me.

**Comment by weepy** [comment]
but a property might be bound to several places ?

**Comment by nevf** [comment]
Good point, but not that common. How about returning an array of matching elements?

**Comment by weepy** [comment]
I'll have a think about how to implement. Remind me of the use case?

**Comment by weepy** [comment]
I know you say " reducing knowledge of the markup" but that's not really a
use case, more a philosophy

**Comment by weepy** [comment]
if you wanted to try it out, you could try adding something like the following to around line 248: 

```
each(deps, function(dep) {
  dep.__boundTo = dep.__boundTo || []
  dep.__boundTo.push(el)
})
```

**Comment by nevf** [comment]
Thanks for that. For some reason I don't understand my model usage doesn't have any dependencies so `deps` is empty.

This is my code:

```
EditLinkDlg.model = { editLinkText: o_O(), editLinkURI: o_O(), editLinkEmail: o_O(), editLinkBookmark: o_O() };
o_O.bind( EditLinkDlg.model, '#editLinkDlg' );
```

This is a one time initialization and then whenever the model is used I execute:

```
// Update the model
EditLinkDlg.model.editLinkText( _link.text );
EditLinkDlg.model.editLinkURI( _link_uri );
....

```

**Comment by weepy** [comment]
can you pastie a minimal example that show's this ?
