### ISSUE TITLE
Multiple data-binds on an element

### ISSUE THREAD

**Issue by nevf** [weepy/o_O#59]
I tried:

```
<button data-bind="text:promptDlgOk" data-bind="visible:has_ok_button"></button>
```

and couldn't get it to work. It appears as though a given element can only have one data-bind. Can you confirm that's the case or am I doing something wrong?

Thanks, Neville

**Comment by weepy** [comment]
do

<button data-bind="text:promptDlgOk; visible:has_ok_button"></button>

**Comment by nevf** [comment]
@weepy Thanks, I didn't think to try that. Too obvious.
